### ISSUE TITLE
URLs are not working anymore

### ISSUE THREAD

**Issue by shefik** [zikula/core#2227]
URLs are not working anymore. Install Zikula 1.4.0 build 416. After a new installation, it redirects to:

/administration/panel

However, a 404 error is thrown.

All pages of the site (except for the homepage) also throw a 404 error.

**Comment by craigh** [comment]
@Guite this looks like a workflow issue again.

> [1] Exception: No permission to execute action: submit [permission]
    at n/a
        in /Applications/MAMP/htdocs/140/lib/legacy/Zikula/Workflow.php line 193

>    at Zikula_Workflow->executeAction('submit', object(RouteEntity), 'initial')
        in /Applications/MAMP/htdocs/140/lib/legacy/Zikula/Workflow/Util.php line 176

>    at Zikula_Workflow_Util::executeAction('none', object(RouteEntity), 'submit', 'route', 'ZikulaRoutesModule', 'id')
        in /Applications/MAMP/htdocs/140/system/ZikulaRoutesModule/Util/Base/WorkflowUtil.php line 192

>    at Zikula\RoutesModule\Util\Base\WorkflowUtil->executeAction(object(RouteEntity), 'submit')
        in /Applications/MAMP/htdocs/140/system/ZikulaRoutesModule/Entity/Repository/Route.php line 136

>    at Zikula\RoutesModule\Entity\Repository\Route->addRouteCollection(object(ZikulaAdminModule), object(RouteCollection))
        in /Applications/MAMP/htdocs/140/system/ZikulaRoutesModule/Entity/Repository/Route.php line 73

>    at Zikula\RoutesModule\Entity\Repository\Route->reloadAllRoutes()
        in /Applications/MAMP/htdocs/140/system/ZikulaRoutesModule/Listener/InstallerListener.php line 76

>    at Zikula\RoutesModule\Listener\InstallerListener->modulePostInstalled(object(ModuleStateEvent), 'module.postinstall', object(TraceableEventDispatcher))
        in  line 

>    at call_user_func(array(object(InstallerListener), 'modulePostInstalled'), object(ModuleStateEvent), 'module.postinstall', object(TraceableEventDispatcher))
        in /Applications/MAMP/htdocs/140/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php line 61

>    at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ModuleStateEvent), 'module.postinstall', object(Zikula_EventManager))
        in  line 

>    at call_user_func(object(WrappedListener), object(ModuleStateEvent), 'module.postinstall', object(Zikula_EventManager))
        in /Applications/MAMP/htdocs/140/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php line 164

>    at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener)), 'module.postinstall', object(ModuleStateEvent))
        in /Applications/MAMP/htdocs/140/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php line 53

>    at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('module.postinstall', object(ModuleStateEvent))
        in /Applications/MAMP/htdocs/140/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php line 167

>    at Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('module.postinstall', object(ModuleStateEvent), null)
        in /Applications/MAMP/htdocs/140/lib/legacy/Zikula/EventManager.php line 99

>    at Zikula_EventManager->dispatch('module.postinstall', object(ModuleStateEvent))
        in /Applications/MAMP/htdocs/140/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php line 112

>    at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('module.postinstall', object(ModuleStateEvent))
        in /Applications/MAMP/htdocs/140/lib/Zikula/Bundle/CoreInstallerBundle/Controller/AjaxInstallController.php line 321

>    at Zikula\Bundle\CoreInstallerBundle\Controller\AjaxInstallController->reloadRoutes()
        in /Applications/MAMP/htdocs/140/lib/Zikula/Bundle/CoreInstallerBundle/Controller/AjaxInstallController.php line 121

>    at Zikula\Bundle\CoreInstallerBundle\Controller\AjaxInstallController->executeStage('reloadroutes')
        in /Applications/MAMP/htdocs/140/lib/Zikula/Bundle/CoreInstallerBundle/Controller/AjaxInstallController.php line 67

>    at Zikula\Bundle\CoreInstallerBundle\Controller\AjaxInstallController->ajaxAction(object(Zikula_Request_Http))
        in  line 

>    at call_user_func_array(array(object(AjaxInstallController), 'ajaxAction'), array(object(Zikula_Request_Http)))
        in /Applications/MAMP/htdocs/140/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 145

>    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Zikula_Request_Http), '1')
        in /Applications/MAMP/htdocs/140/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 66

>    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /Applications/MAMP/htdocs/140/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 64

>    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /Applications/MAMP/htdocs/140/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 186

>    at Symfony\Component\HttpKernel\Kernel->handle(object(Zikula_Request_Http))
        in /Applications/MAMP/htdocs/140/index.php line 25

**Comment by cmfcmf** [comment]
Related lines: 
- https://github.com/zikula/core/commit/73db04b5981e84f28cf1417a87ad363c07652966#diff-e9adc36e907cf03bcaf731eafac33843L27
- https://github.com/zikula/core/blob/1.4/src/system/ZikulaRoutesModule/Resources/docs/model/Routes.mostapp

**Comment by craigh** [comment]
fixed by #2228

**Comment by shefik** [comment]
@craigh It is not fixed. I tried Zikula 1.4.0 build 417 with a new installation. Same issue persists.

**Comment by craigh** [comment]
It worked for me fine

**Comment by Kaik** [comment]
Same for me yesterday I have installed it at least 5 times web install everything is fine. @shefik I remember similar behaviour some time ago and do you have mod_rewrite installed? 
You can try to change module_vars - stripentrypoint from 1 to 0 using phpmyadmin and see if you can reach any other page than home.

**Comment by shefik** [comment]
I use MAMP, so mod_rewrite is already installed.

**Comment by craigh** [comment]
> Same issue persists.

When I tested for this ticket initially, I received a pop exception during the ajax installation stage, which I copied the contents above. If you are still receiving an error, please copy the contents/trace here.

**Comment by shefik** [comment]
Okay, I got it working again, Looks like MAMP was configured not to allow overrides to ".htaccess", which is needed. So, that part is fine.

Now I'm wondering how you are actually installing Zikula. There used to be a file "/install.php", but that no longer exists. Without that file, the site redirects to "/install", but access is denied with the error message:

"Forbidden

You don't have permission to access /install on this server."

So, the only way I am able to install to use "/install.php" from an older build. Using "/install.php" does still work. How you are you installing Zikula without that file?

**Comment by craigh** [comment]
Apparently you are overwriting old files with the new ones? Please follow the [actual install instructions](https://github.com/zikula/core/blob/1.4/INSTALL-1.4.0.md)

**Start with an empty directory** and follow the instructions. There should be no `/install` directory at all. If there is, you are using the old installer which is removed in current builds.
