### ISSUE TITLE
Routing - SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by shefik** [zikula/core#2587]
In Zikula 1.4.1 build 35, the browser is throwing this error:

`SyntaxError: Unexpected token '<'`

In this file:

`/js/routing?callback=fos.Router.setData`

Looks like the JSON data is being wrapped in the theme template.

**Comment by craigh** [comment]
do you have any more information? How to I reproduce this?

**Comment by craigh** [comment]
can you copy the content of the file from the console and paste it here?

**Comment by shefik** [comment]
The JSON data in the file is including the theme's header and footer. It's not just a JSON response, as expected.

Just do a new install of build 35. After you login at the homepage, view source in the browser for that routing file.

**Comment by craigh** [comment]
thanks! that actually helps a lot.

**Comment by craigh** [comment]
@shefik @cmfcmf I have pushed a fix for this please test.

**Comment by shefik** [comment]
@craigh Tested build 36. It's fixed. Still have the issue about missing CSS though (from the other ticket).

**Comment by craigh** [comment]
great to hear. As you saw, the issue with the other ticket is about the jenkins build. Hoping Christian will take that one. thanks for reporting and helping trouble shoot.
