### ISSUE TITLE
Blocks error in Permissions view

### ISSUE THREAD

**Issue by craigh** [zikula/core#2721]
![screen shot 2016-01-06 at 5 36 49 pm](https://cloud.githubusercontent.com/assets/350048/12156963/293d8608-b49c-11e5-9ad9-913a0bd888ff.png)

error thrown here: https://github.com/zikula/core/blob/8db098c77b0c7249d700c26f788eeb425946e352/src/lib/legacy/util/BlockUtil.php#L338-L338

**Comment by Guite** [comment]
Just checking for `BlockHandlerInterface` instead of `AbstractBlockHandler` should resolve this.

**Comment by craigh** [comment]
> Just checking for BlockHandlerInterface instead of AbstractBlockHandler should resolve this.

It hides the problem, but doesn't solve it. please see my PR #2724
