### ISSUE TITLE
RSS not working in 1.4.1

### ISSUE THREAD

**Issue by pheski** [zikula/core#2751]
There is a long thread about this (http://zikula.org/forums/topic/59910/31?lang=en) on the forum, and I am not sure if this belongs under the News module, themes, or core. I cannot find the RSS issue already listed in these places. RSS is obviously an important feature.

Seems to me it should either be a bug ticket or there should be a comment saying it will be fixed with 1.4.x or a pointer to other information about the status.

Thanks.

**Comment by pheski** [comment]
This is the error I get when I try RSS:

<?xml version="1.0" encoding="utf8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <link rel="alternate" type="text/html" href="http://www.petereliasmd.com/index.php" />
    <link rel="self" type="application/atom+xml" href="/" />
    <title>petereliasmd</title>
    <subtitle>In my opinion...</subtitle>
    <id>tag:www.petereliasmd.com,1969-12-31:petereliasmd</id>
    <updated>2016-01-28T04:43:42Z</updated>
    <author>
        <name>pheski@me.com</name>
    </author>
    <generator>Zikula</generator>
    <rights>Copyright petereliasmd</rights>
    <div id="z-maincontent" class="z-module-news">        <h1>Oops! An Error Occurred</h1>
        <h2>The server returned a "500 Internal Server Error".</h2>

        <div>
            Something is broken. Please let us know what you were doing when this error occurred.
            We will fix it as soon as possible. Sorry for any inconvenience caused.
        </div><br />
        <div class="alert alert-warning">User Error: Smarty error: [in rss/index.tpl line 12]: [plugin] modifier &#039;updated&#039; is not implemented (core.load_plugins.php, line 118)</div></div>
</feed>

**Comment by eledril** [comment]
I'll be happy to try out any suggestions to help resolve this issue.

**Comment by eledril** [comment]
Something else. When I'm logged into the site (using IE) I get the following error:
System does not support the specified encoding.
 Line: 1 Character: 38

`<?xml version="1.0" encoding="utf8"?>`

**Comment by eledril** [comment]
So when I click on the RSS icon in IE, it goes to "index.php?module=news&type=user&func=view&theme=RSS" and throws the error above.
The Theme Name shows up under Themes as "ZikulaRssTheme" so shouldn't it point to "index.php?module=news&type=user&func=view&theme=ZikulaRssTheme"?
When I try that url it just goes to the News Main page, as if you went to "index.php?module=news&type=user&func=main".
Part of the issue for me seems to be that when I try to preview any Theme when not logged in, it sends me back to the Home Page.
I have "Allow users to change themes" checked as well as "CSS/JS optimisation" but nothing else is checked and "Use 'trimwhitespace' output filter".
Could updating some of the code in one of the Theme files to point it to ZikulaRssTheme rather than just RSS help?

**Comment by eledril** [comment]
@pheski Any ideas?

**Comment by pheski** [comment]
As far as I can tell, RSS doesn’t work in 1.4.0 or 1.4.1.  Moving back to 1.3.x versions is not an option for me at the moment, so I have not looked back to see what the newest site with working RSS is.

I am assuming that, at some point, this will be addressed, either in core or in a theme. (I do not understand whether the problem is one related to core or theme.)

What baffles me the most is that RSS seems not to be deemed important enough to be higher priority.  (I understand that there is a small core of volunteer developers and that the emphasis is on getting 1.4.2 ready.)

Peter

**Comment by pheski** [comment]
Perhaps the question to be answered is: is there a theme that **anyone** is using in 1.4.0 or 1.4.1 where RSS works?

**Comment by eledril** [comment]
My biggest problem right now is the RSS issue. My site is a News website which uses the RSS feed to send content to Google News, my social media accounts, etc. So because the RSS feed isn't working, then the amount of traffic coming to my site has dropped.

**Comment by eledril** [comment]
I just checked the RSS feed in your site (in IE) @pheski and it's doing the same thing as mine, with it just going back to the News page.

**Comment by pheski** [comment]
I guess I have resigned myself to the fact that Zikula sites using 1.4+ are not RSS capable, which makes the current official version cripple ware in terms of blogs or community sites. What puzzles me is that no one seems to think this is an issue. Certainly, no one has been willing to say what the plan or timetable is for resolving this.

I have moved two sites away from Zikula and will be gradually moving my other sites away unless there is visible progress and this is fixed in 1.4.2.  It is a shame and I am very sad but not angry.  I like Zikula and would like to stay and see it succeed. I am aware that the development team is small and all volunteers. But loyalty and history do not outweigh function.



Peter

**Comment by craigh** [comment]
it's not fixed in 1.4.2. sorry. IMO this is probably an issue with News. But development on News [stopped 3 years ago](https://github.com/zikula-modules/News/graphs/contributors) and nobody has picked up the slack. It is still stuck in Core-1.2 status (basically). I'm too busy with core to develop modules.

Consider learning to code and fixing it. seriously. That's how I got involved here. It's not impossible. Someone has to start to step up and contribute.

**Comment by eledril** [comment]
> Consider learning to code and fixing it. seriously. That's how I got involved here. It's not impossible. Someone has to start to step up and contribute.

Sounds like a plan. What resources would you recommend to get me started on learning to code?

**Comment by pheski** [comment]
Fair enough, and I don’t disagree. I have been considering it. You make it sound easier than it feels to me.

When I joined the PostNuke community almost 12 years ago I was marginally competent with HTML and  CSS. I began to teach myself PHP with an eye towards becoming a code contributor. My 70 hour a week job as a primary care physician limited me considerably and I never got there. I helped with documentation and testing, and learned enough PHP to be able to work some around the edges with other people’s code. I never reached a level where I could create original functionality.

Zikula has evolved quite a distance since then. When I started winding down my medical responsibilities, I returned to Zikula thinking I would resume being active and learn to contribute. I set up a local development environment using MAMP, but then ground to a halt. I find myself overwhelmed: Symfony, Doctrine, Bootstrap, jQuery….I truly do not know where/how to begin.

Hope is not a strategy. (My father used to irritate me with: "Hoffen und harren macht manchen zum Narren.”)  I suppose I should review my PHP, then invest in some online courses on Symphony and jQuery and look through the Forum for information on moving old modules forward. At best, I can help. At worst, I learn.

Where would you suggest someone start learning if they wanted to be able to help with Zikula?  Would it be worth a blog post talking about the important pieces and how they fit: “So you want to help? Here’s a road map…”

Peter

**Comment by pheski** [comment]
Looks like Chris and I have the same basic question. Where does one start?

Peter

**Comment by Guite** [comment]
A personal advice:

1. Server-side programming I: PHP, security, databases, Doctrine
2. Server-side programming II: Design pattern, Symfony, Twig, Zikula-specifics
3. Frontend technologies: HTML 5, CSS, Bootstrap
4. Client-side programming: JavaScript, jQuery, Bootstrap JS
(5. Dynamically generated JS - only needed in special cases nowadays, since HTML 5 data attributes and CSS-like selectors in jQuery allow a more convenient replacement)

**Comment by Guite** [comment]
Note I have in mind rewriting Content as well as News based on ModuleStudio 0.7 at some point. This needs some time though, as the 1.4 generator needs to become stable first. Also Content will certainly be done before News.

**Comment by pheski** [comment]
Thank you.  Lots of stuff to learn, but it is nice to have at least a tentative map.

Peter

**Comment by craigh** [comment]
I agree with @Guite on the order - learn PHP as a language first. Thousands of places online for this (here's [one](https://www.codecademy.com/learn/php)). Install MAMP/WAMP code locally, experiment. fail. try. Ask questions - the good part about learning to code now is you have millions of resources online. Best place I have found to ask questions is [stackoverflow](http://stackoverflow.com/). Many people there willing to help you (and me) learn everything from the basics to advanced stuff. (use the search engine!). 

Next - STUDY the documentation for our vendors - Symfony, Doctrine, Bootstrap, etc. The *reason* we use these libraries is that they are VERY heavily used with communities willing to help, documentation like crazy. *I* use the docs all the time. I'm just a hack - I am a *band director* in real life (I'm at work right now!). I only learned to code PHP because I wanted an [interactive website](http://www.westernbands.net) for my students.

You'll have questions. great! I'm (almost always) happy to answer questions about HOW to do something for yourself. Please ask. You'll notice on our own forum many questions like this (recently from @paustian).

Understand, it is a long process (unless you're a genius I guess) I started in 2000 or so. so 16 years later, I feel like I might know what I am doing, but I still use all those resources.

Best wishes :wink:

**Comment by cmfcmf** [comment]
The RSS problem should be fixed by https://github.com/zikula-modules/News/commit/9ac5dda55db59dc766e4e2d09cb6b714f5edbd18. You can try to apply these changes yourself inside the News module.

**Comment by eledril** [comment]
Thank you so much. I have made the changes but I'm still getting the same message. I cleared the cache without success. It may just need some time to take effect. I'll check back later and see what happens.

**Comment by cmfcmf** [comment]
Could you please post the link to your site again so that I can take a look
at the error?

Chris Pelletier <notifications@github.com> schrieb am Mi., 23. März 2016 um
19:08 Uhr:

**Comment by eledril** [comment]
http://northumberlandview.ca and the feed should be at http://www.northumberlandview.ca/index.php?module=news&type=user&func=view&theme=RSS

**Comment by rallek** [comment]
![northumberland](https://cloud.githubusercontent.com/assets/935250/13996410/dcac6ede-f12d-11e5-85ab-7ad5d6a59a1d.jpg)
I can see this

**Comment by cmfcmf** [comment]
Does it change if you are logged in and view the url?

rallek <notifications@github.com> schrieb am Mi., 23. März 2016 um
19:32 Uhr:

**Comment by eledril** [comment]
When I'm logged in as an administrator it switches to the Bootstrap Theme. I tried the url and got the following error.

> System does not support the specified encoding.
>  Line: 1 Character: 38
> 
> <?xml version="1.0" encoding="utf8"?>

**Comment by cmfcmf** [comment]
@eledril Please add the following permission to your site: 
![image](https://cloud.githubusercontent.com/assets/2145092/13997132/d995438a-f130-11e5-83d6-82558cf65c62.png)

This will allow everyone and not only admins to see the RSS feed, which is a first step into the right direction. Let me know when it's done so that I can take a look myself again.

**Comment by eledril** [comment]
Done and working.

**Comment by cmfcmf** [comment]
Okay, it's getting there. It's still not quite right (there is a `<div class="z-maincontent">` in the RSS, but I'll close this issue and open another one detailing all the current problems.

**Comment by cmfcmf** [comment]
New issue: https://github.com/zikula/core/issues/2819

**Comment by pheski** [comment]
:-)
