### ISSUE TITLE
Unable to modify English (en) strings

### ISSUE THREAD

**Issue by shefik** [zikula/core#3132]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6

### Expected behavior

The English (en) strings should be modified.

### Actual behavior

The English (en) strings not not modified.

### Steps to reproduce

Create these files, and modify strings:

`/app/Resources/translations/zikula.en.mo`
`/app/Resources/translations/zikula.en.po`

Even though the set domain is "zikula", the files don't seem to be working for modifying "en" strings.

**Comment by craigh** [comment]
please take a look at an actual build with extracted strings from the ci server. You will see extracted catalogs and their contents.

**Comment by shefik** [comment]
In the builds, there are files placed here: `/app/Resources/translations`.

Renaming the file `/app/Resources/translations/zikulazauthmodule.template.po` to `/app/Resources/translations/zikulazauthmodule.en.po` does not work.

**Comment by shefik** [comment]
There are strings in templates that are not even contained in the Zikula POT file. For example, this template:

`/system/ZAuthModule/Resources/views/Account/changeEmail.html.twig`

has the string:

`__('Email address manager')`

I downloaded the latest `Zikula_Core-1.4-POT` file from http://ci.zikula.org, but the string is not there. It's also not in the file `Zikula_Core-master-POT`.

**Comment by craigh** [comment]
refs #3117

**Comment by craigh** [comment]
I think this is a translation **domain** problem. I think if you put all the strings into `zikula.po` then it works ok.

**Comment by craigh** [comment]
ping @Kaik any thoughts here please?

**Comment by shefik** [comment]
@craig I tried that. Even the zikula.po english translation is not working, even though the zikula domain is being set.

**Comment by craigh** [comment]
you have to clear the cache after

**Comment by shefik** [comment]
I did clear the cache.

**Comment by craigh** [comment]
`translations/zikula.en.po`

**Comment by craigh** [comment]
this should be fixed. please let me know if there are still problems.

**Comment by shefik** [comment]
This still does not appear to be working for me. I created the translation file here:

`/app/Resources/translations/zikula.en.po`

I edited the string `Blocks list` to `Blocks List`, which is found at the page `/blocks/admin/view`, but I am still seeing `Blocks list` on the reloaded page.
