### ISSUE TITLE
Enable to create new categorie on 2.0.2

### ISSUE THREAD

**Issue by PierreNau** [zikula/core#3833]
Hi!
While creating a new categorie I get the following message: 
_500: Internal Server Error_
I thought this issue sorted out?
Many thanks for your help!

**Comment by Guite** [comment]
Hi,

can you please check your browser's console to see whether an error is shown there?

**Comment by PierreNau** [comment]
Below what I got from the console
Failed to load resource: the server responded with a status of 500 (Internal Server Error)   contextMenu/edit/33

**Comment by PierreNau** [comment]
Hereafter the message from the console:
<font color=red>Failed to load resource: the server responded with a status of 500 (Internal Server Error)</font>

**Comment by Guite** [comment]
Is it possible that this problem occurs only for nodes containing children? Please check whether it works for leaf nodes (without any children).

**Comment by PierreNau** [comment]
The problem occurs for leaf nodes as well ...
I experienced the same while trying to change the name with an existind category.
The only thing working is drag & drop a  category from a folder to an other one while having the same message 500 (Internal Server Error)

**Comment by Guite** [comment]
I just tried to reproduce this and got an idea: do you have additional core locales in your system (`app/Resources/translations/`)? If yes please try to rename this directory and see if it works then.

**Comment by Guite** [comment]
This problem is related to determination of locale names. I can reproduce a class loading error when accessing `Symfony\Component\Intl\Intl::getLanguageBundle()`. Further investigating...

**Comment by Guite** [comment]
@PierreNau I think I fixed the problem. Can you confirm that it works with the patch shown in #3834 ?

**Comment by PierreNau** [comment]
Thank you Guite for your help and investigation.
However, the problem is not fixed with the patch. 
Moreover, I did not add additional core languages yet (French in my case)

**Comment by Guite** [comment]
Can you explain in detail how to reproduce the 500 error after applying the patch? Does it occur when opening the edit modal window or after submitting the form?

**Comment by paustian** [comment]
The bug is still there in Core 2.0.2. To reproduce the error do a fresh install of Zikula 2.0.2. When finished go to the Categories module and try to create a new category, it can be anywhere. When you hit submit you get a 500 error. This is what is shown in the javascript console

`jquery.js:8630 POST http://localhost:8888/zikula_2_0/categories/admin/category/contextMenu 500 (Internal Server Error)
  | send | @ | jquery.js:8630
-- | -- | -- | --
  | ajax | @ | jquery.js:8166
  | (anonymous) | @ | ZikulaCategoriesModu…ategory.List.js:232
  | dispatch | @ | jquery.js:4435
  | elemData.handle | @ | jquery.js:4121
`
If you look at ZikulaCategoriesModule.Category.List.js this is the code around line 232
` $.ajax({
               type: 'POST',
                url: Routing.generate('zikulacategoriesmodule_node_contextmenu', {action: data.action, id: entityId}),
              data: pars
        }).success(function(result) {`
Could it be the route is just bad?

**Comment by Guite** [comment]
Thanks @paustian I am going to extend #3834 to fix this today.

**Comment by PierreNau** [comment]
Hi Guite,
Nothing to add to Paustian's message. He described exactly what I experienced.
I did a fresh install as well with no improvement.
Thank you for your help.

**Comment by Guite** [comment]
First I could not reproduce this using 1.5.3-git with the patch from #3834.
Thus I will now merge #3834 into 1.5, 2.0 and master branches and continue testing using 2.0.3-git afterwards.

**Comment by Guite** [comment]
fixed in https://github.com/zikula/core/commit/db96a43fdb1eb7057cdae828e54773131bb404db
